SELECT * FROM REGIONS;

SELECT * FROM COUNTRIES;

SELECT * FROM REGIONS, COUNTRIES;

SELECT COUNTRY_ID,COUNTRY_NAME, REGION_NAME
FROM COUNTRIES A
INNER JOIN REGIONS B
ON (A.REGION_ID = B.REGION_ID);

SELECT * 
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID);

SELECT B.*
FROM EMPLOYEES A
NATURAL JOIN DEPARTMENTS B;

SELECT *
FROM COUNTRIES
NATURAL JOIN REGIONS;




SELECT *
FROM EMPLOYEES;


