SELECT NVL(COMMISSION_PCT, 0) AS COMMISSION_PCT
FROM EMPLOYEES;



SELECT MAX(EMPLOYEE_ID) FROM EMPLOYEES;


CREATE OR REPLACE PROCEDURE SP_INSERTAR_EMPLEADO(
        P_FIRST_NAME VARCHAR2,
        P_LAST_NAME VARCHAR2,
        P_EMAIL VARCHAR2,
        P_PHONE_NUMBER VARCHAR2,
        P_HIRE_DATE DATE,
        P_JOB_ID VARCHAR2,
        P_SALARY NUMBER,
        P_COMMISSION_PCT NUMBER,
        P_MANAGER_ID INTEGER,
        P_DEPARTMENT_ID INTEGER
) AS 
  --VARIABLES
BEGIN
    INSERT INTO EMPLOYEES(
        EMPLOYEE_ID,
        FIRST_NAME,
        LAST_NAME,
        EMAIL,
        PHONE_NUMBER,
        HIRE_DATE,
        JOB_ID,
        SALARY,
        COMMISSION_PCT,
        MANAGER_ID,
        DEPARTMENT_ID
      )
      VALUES
      (
        SQ_EMPLOYEE_ID.NEXTVAL,
        P_FIRST_NAME,
        P_LAST_NAME,
        P_EMAIL,
        P_PHONE_NUMBER,
        P_HIRE_DATE,
        P_JOB_ID,
        P_SALARY,
        P_COMMISSION_PCT,
        P_MANAGER_ID,
        P_DEPARTMENT_ID
      );
      COMMIT;
END;


SELECT *
FROM DEPARTMENTS;

EXECUTE SP_INSERTAR_EMPLEADO(P_FIRST_NAME => 'JUAN',P_LAST_NAME => 'PEREZ',P_EMAIL => 'juan@gmail.com',P_PHONE_NUMBER => '12312.23423.345',P_HIRE_DATE => sysdate,P_JOB_ID => 'AD_VP',P_SALARY => 21312,P_COMMISSION_PCT => 0.12, P_MANAGER_ID => 101, P_DEPARTMENT_ID => 20);
EXECUTE SP_INSERTAR_EMPLEADO('JUAN','PEREZ','juan2@gmail.com','12312.23423.345',sysdate,'AD_VP',21312,0.12, 101, 20);

SET SERVEROUTPUT ON;

DECLARE
  V_CODIGO_EMPLEADO_INSERTADO INTEGER;
BEGIN
  SP_INSERTAR_EMPLEADO(
      P_FIRST_NAME => 'JUAN',
      P_LAST_NAME => 'PEREZ',
      P_EMAIL => 'juan4@gmail.com',
      P_PHONE_NUMBER => '12312.23423.345',
      P_HIRE_DATE => sysdate,
      P_JOB_ID => 'AD_VP',
      P_SALARY => 21312,
      P_COMMISSION_PCT => 0.12, 
      P_MANAGER_ID => 101, 
      P_DEPARTMENT_ID => 20,
      P_EMPLOYEE_ID => V_CODIGO_EMPLEADO_INSERTADO);
    DBMS_OUTPUT.PUT_LINE('CODIGO INSERTADO: '||V_CODIGO_EMPLEADO_INSERTADO);
END;
