SELECT * 
FROM TBL_EMPLEADOS;

SELECT *
FROM TBL_CARGOS;

--3 SCRIPTS CON EL MISMO RESULTADO
--UTILIZANDO UN INNER JOIN
SELECT A.NOMBRE_EMPLEADO, A.GENERO, A.SUELDO_NETO,
        B.NOMBRE_CARGO
FROM TBL_EMPLEADOS A
INNER JOIN TBL_CARGOS B
ON (A.CODIGO_CARGO = B.CODIGO_CARGO);


--UTILIZANDO UN NATURAL JOIN (SE OMITE LA SENTENCIA ON)
SELECT A.NOMBRE_EMPLEADO, A.GENERO, A.SUELDO_NETO,
        B.NOMBRE_CARGO
FROM TBL_EMPLEADOS A
NATURAL JOIN TBL_CARGOS B;

--UTILIZANDO UN PRODUCTO CARTESIANO Y APLICANDO UN WHERE
--PARA FILTRAR UNICAMENTE LOS REGISTROS QUE COINCIDEN
SELECT A.NOMBRE_EMPLEADO, A.GENERO, A.SUELDO_NETO,
        B.NOMBRE_CARGO
FROM  TBL_EMPLEADOS A, 
      TBL_CARGOS B
WHERE A.CODIGO_CARGO = B.CODIGO_CARGO;


--Utilizar left join para evitar perdida de 
--informacion de la tabla A
SELECT A.NOMBRE_EMPLEADO, A.GENERO, A.SUELDO_NETO,
        B.NOMBRE_CARGO
FROM TBL_EMPLEADOS A
LEFT JOIN TBL_CARGOS B
ON (A.CODIGO_CARGO = B.CODIGO_CARGO);

--Hacer un Left join utilizando un producto cartesiano
SELECT A.NOMBRE_EMPLEADO, A.GENERO, A.SUELDO_NETO,
        B.NOMBRE_CARGO
FROM  TBL_EMPLEADOS A, 
      TBL_CARGOS B
WHERE A.CODIGO_CARGO = B.CODIGO_CARGO(+);

--Obtener todos los empleados que no tienen un cargo definido
SELECT A.NOMBRE_EMPLEADO, A.GENERO, A.SUELDO_NETO,
       B.CODIGO_CARGO, B.NOMBRE_CARGO
FROM TBL_EMPLEADOS A
LEFT JOIN TBL_CARGOS B
ON (A.CODIGO_CARGO = B.CODIGO_CARGO)
WHERE B.CODIGO_CARGO IS NULL;


--Utilizar right join para mostrar todos los cargos 
--sin importar si no hay empleados con dicho cargo
SELECT A.NOMBRE_EMPLEADO, A.GENERO, A.SUELDO_NETO,
        B.NOMBRE_CARGO
FROM TBL_EMPLEADOS A
RIGHT JOIN TBL_CARGOS B
ON (A.CODIGO_CARGO = B.CODIGO_CARGO);

--Hacer un Right join utilizando un producto cartesiano
SELECT A.NOMBRE_EMPLEADO, A.GENERO, A.SUELDO_NETO,
        B.NOMBRE_CARGO
FROM  TBL_EMPLEADOS A, 
      TBL_CARGOS B
WHERE A.CODIGO_CARGO(+) = B.CODIGO_CARGO;


--Mostrar empleados y cargos, independientemente
--si hay empleados sin cargo o si hay cargos que no
--estan asignados a ningun empleado
SELECT A.NOMBRE_EMPLEADO, A.GENERO, A.SUELDO_NETO,
        B.NOMBRE_CARGO
FROM TBL_EMPLEADOS A
FULL OUTER JOIN TBL_CARGOS B
ON (A.CODIGO_CARGO = B.CODIGO_CARGO);

--Hacer un Full outer join utilizando un producto cartesiano
SELECT A.NOMBRE_EMPLEADO, A.GENERO, A.SUELDO_NETO,
        B.NOMBRE_CARGO
FROM  TBL_EMPLEADOS A, 
      TBL_CARGOS B
WHERE A.CODIGO_CARGO(+) = B.CODIGO_CARGO(+);


--FILTRAR LOS EMPLEADOS QUE NO TIENEN CARGO
-- Y FILTRAR LOS CARGOS QUE NO ESTAN ASIGNADOS 
-- A NINGUN EMPLEADO.
SELECT A.CODIGO_EMPLEADO,
        A.NOMBRE_EMPLEADO, 
        A.GENERO, A.SUELDO_NETO,
        B.CODIGO_CARGO,
        B.NOMBRE_CARGO
FROM TBL_EMPLEADOS A
FULL OUTER JOIN TBL_CARGOS B
ON (A.CODIGO_CARGO = B.CODIGO_CARGO)
WHERE A.CODIGO_EMPLEADO IS NULL 
OR B.CODIGO_CARGO IS NULL;


select * 
from tmp_salario_total;
select *
from tbl_empleados;

select a.nombre_empleado,
    a.sueldo_neto,
    b.salario as salario_total,
    round((a.sueldo_neto / b.salario)*100,2) as porcentaje
from tbl_empleados a,
    tmp_salario_total b;






