---sintaxis crear vistas
CREATE OR REPLACE VIEW NOMBRE_VISTA AS
<CONSULTA>;


CREATE OR REPLACE VIEW VW_DESPERFECTOS AS
SELECT A.NUMERO_PLACA,
    B.COSTO_NETO AS COSTO_DESPERFECTO,
    C.NOMBRE_DESPERFECTO,
    C.COSTO_BASE
FROM TBL_VEHICULOS A
INNER JOIN TBL_DESPERFECTO_X_VEHICULO B
ON (A.NUMERO_PLACA = B.NUMERO_PLACA)
INNER JOIN TBL_DESPERFECTOS C
ON (B.CODIGO_DESPERFECTO = C.CODIGO_DESPERFECTO);

SELECT *
FROM VW_DESPERFECTOS;

SELECT count(*) as cantidad_registros
FROM VW_DESPERFECTOS;

SELECT count(1)
FROM VW_DESPERFECTOS;

SELECT NOMBRE_DESPERFECTO,
      COUNT(*) AS CANTIDAD_DESPERFECTOS,
      SUM(COSTO_DESPERFECTO) COSTO
FROM VW_DESPERFECTOS
GROUP BY NOMBRE_DESPERFECTO;
