--Obtener los asientos disponibles por vuelo
SELECT *
FROM TBL_AVIONES;

SELECT *
FROM TBL_VUELOS;


SELECT CODIGO_VUELO,
  CANTIDAD_ASIENTOS
FROM TBL_VUELOS A
INNER JOIN TBL_AVIONES B
ON (A.CODIGO_AVION = B.CODIGO_AVION);


SELECT CODIGO_VUELO, COUNT(1) CANTIDAD_ASIENTOS_VENDIDOS
FROM TBL_FACTURA_DETALLE
GROUP BY CODIGO_VUELO;



SELECT LA_CONSULTA_DE_ARRIBA - CONSULTA_DE_ABAJO
FROM DUAL;


SELECT A
FROM B
WHERE C;


SELECT A.CODIGO_VUELO,
    A.CANTIDAD_ASIENTOS AS CANTIDAD_ASIENTOS_TOTALES,
    B.CANTIDAD_ASIENTOS_VENDIDOS,
    (A.CANTIDAD_ASIENTOS - B.CANTIDAD_ASIENTOS_VENDIDOS) AS ASIENTOS_DISPONIBLES
FROM (
  SELECT CODIGO_VUELO,
    CANTIDAD_ASIENTOS
  FROM TBL_VUELOS A
  INNER JOIN TBL_AVIONES B
  ON (A.CODIGO_AVION = B.CODIGO_AVION)
) A
INNER JOIN (
  SELECT CODIGO_VUELO, COUNT(1) CANTIDAD_ASIENTOS_VENDIDOS
  FROM TBL_FACTURA_DETALLE
  GROUP BY CODIGO_VUELO
) B
ON (A.CODIGO_VUELO = B.CODIGO_VUELO);
