--CALCULAR EL PORCENTAJE DE CRECIMIENTO ANUAL 
--DE SALARIOS TOMANDO COMO REFERENCIA LA FECHA DE CONTRATACION
-- (HIRE_DATE), HACER LA COMPARACION ENTRE 2006 Y 2005
-- %CRECIMIENTO = SALARIOS 2006 / SALARIOS 2005
--Obtener salario total para un año especifico
SELECT TO_CHAR(HIRE_DATE, 'YYYY') AS ANIO, 
      SUM(SALARY) AS SALARY_TOTAL
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE, 'YYYY') = 2006
GROUP BY TO_CHAR(HIRE_DATE, 'YYYY')
ORDER BY ANIO;



SELECT 
    1-((
      SELECT SUM(SALARY) AS SALARY_TOTAL
      FROM EMPLOYEES
      WHERE TO_CHAR(HIRE_DATE, 'YYYY') = 2006
    )/(
      SELECT SUM(SALARY) AS SALARY_TOTAL
      FROM EMPLOYEES
      WHERE TO_CHAR(HIRE_DATE, 'YYYY') = 2005
    ))
FROM DUAL;





SELECT SUM(SALARY) AS SALARY_TOTAL
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE, 'YYYY') = 2006;

SELECT TO_CHAR(HIRE_DATE, 'YYYY') AS ANIO, 
      SUM(SALARY) AS SALARY_TOTAL
FROM EMPLOYEES
WHERE TO_CHAR(HIRE_DATE, 'YYYY') = 2005
GROUP BY TO_CHAR(HIRE_DATE, 'YYYY')
ORDER BY ANIO;


-----
--Utilizar subconsultas en vez de una tabla.
SELECT *
FROM (
  SELECT *
  FROM (
    SELECT * 
    FROM EMPLOYEES
  )
);

--Obtener el porcentaje del salario correspondiente de un 
--empleado con respecto al salario total
-- % = salario_empleado/salario_total

SELECT *
FROM EMPLOYEES; 

SELECT SUM(SALARY)
FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME,
    SALARY, 
    round((
      SALARY/(
        SELECT SUM(SALARY)
        FROM EMPLOYEES
      )
    )*100,2) AS PORCENTAJE
FROM EMPLOYEES;


--Verificar el porcentaje
SELECT SUM(PORCENTAJE)
FROM (
  SELECT FIRST_NAME, LAST_NAME,
      SALARY, 
      (
        SALARY/(
          SELECT SUM(SALARY)
          FROM EMPLOYEES
        )
      )*100 AS PORCENTAJE
  FROM EMPLOYEES
);

