SELECT CODIGO_CARGO, SUELDO_BASE, NOMBRE_CARGO
FROM tbl_cargos;

SELECT *
FROM tbl_cargos;

SELECT *
FROM tbl_cargos
WHERE CODIGO_CARGO = 4;

--UTILIZANDO >= Y <=
SELECT * 
FROM TBL_CARGOS
WHERE SUELDO_BASE>=10000 AND SUELDO_BASE<=15000;

--UTILIZANDO EL OPERADOR BETWEEN
SELECT * 
FROM TBL_CARGOS
WHERE SUELDO_BASE BETWEEN 10000 AND 15000;


SELECT *
FROM TBL_CARGOS
WHERE CODIGO_CARGO != 4;

SELECT *
FROM TBL_CARGOS
WHERE CODIGO_CARGO <> 4;

SELECT * 
FROM TBL_CARGOS
WHERE CODIGO_CARGO IN (3,2);


SELECT * 
FROM TBL_CARGOS
WHERE NOMBRE_CARGO IN ('Cargo 2', 'Cargo 3');


SELECT *
FROM TBL_CARGOS
WHERE NOMBRE_CARGO LIKE '%arg%o%';


SELECT *
FROM TBL_EMPLEADOS
WHERE LOWER(NOMBRE_EMPLEADO) LIKE LOWER('%aTus%');

--ASIGNAR ALIAS A CAMPOS
SELECT  UPPER(A.NOMBRE_EMPLEADO)  NOMBRE_EMPLEADO_UPPER, 
        LOWER(NOMBRE_EMPLEADO) AS NOMBRE_EMPLEADO_LOWER, 
        NOMBRE_EMPLEADO
FROM TBL_EMPLEADOS A;


SELECT 100+100 AS OPERACION, 'PEDRO' AS NOMBRE 
FROM DUAL;

SELECT CODIGO_CARGO, NOMBRE_CARGO, SUELDO_BASE,
      SUELDO_BASE * 0.05 AS AUMENTO,
      SUELDO_BASE + (SUELDO_BASE * 0.05) AS SUELDO_NETO,
      100+100 AS NUMERO,
      'HOLA' TEXTO
FROM  TBL_CARGOS;










