SELECT NVL(COMMISSION_PCT, 0) AS COMMISSION_PCT
FROM EMPLOYEES;



SELECT MAX(EMPLOYEE_ID) FROM EMPLOYEES;


create or replace PROCEDURE SP_INSERTAR_EMPLEADO(
        P_EMPLOYEE_ID OUT INTEGER,
        P_FIRST_NAME VARCHAR2,
        P_LAST_NAME VARCHAR2,
        P_EMAIL VARCHAR2,
        P_PHONE_NUMBER VARCHAR2,
        P_HIRE_DATE DATE,
        P_JOB_ID VARCHAR2,
        P_SALARY NUMBER,
        P_COMMISSION_PCT NUMBER,
        P_MANAGER_ID INTEGER,
        P_DEPARTMENT_ID INTEGER,
        P_TRANSACCION_EXITOSA OUT BOOLEAN,
        P_MENSAJE OUT VARCHAR2
) AS 
  --VARIABLES
BEGIN
    P_EMPLOYEE_ID := SQ_EMPLOYEE_ID.NEXTVAL;
    INSERT INTO EMPLOYEES(
        EMPLOYEE_ID,
        FIRST_NAME,
        LAST_NAME,
        EMAIL,
        PHONE_NUMBER,
        HIRE_DATE,
        JOB_ID,
        SALARY,
        COMMISSION_PCT,
        MANAGER_ID,
        DEPARTMENT_ID
      )
      VALUES
      (
        P_EMPLOYEE_ID,
        P_FIRST_NAME,
        P_LAST_NAME,
        P_EMAIL,
        P_PHONE_NUMBER,
        P_HIRE_DATE,
        P_JOB_ID,
        P_SALARY,
        P_COMMISSION_PCT,
        P_MANAGER_ID,
        P_DEPARTMENT_ID
      );
      COMMIT;
      P_TRANSACCION_EXITOSA := TRUE;
      P_MENSAJE := 'TRANSACCION EXITOSA';
      /*IF (SQL%ROWCOUNT = 1) THEN
        P_TRANSACCION_EXITOSA := TRUE;
        P_MENSAJE := 'TRANSACCION EXITOSA';
      ELSE
        P_TRANSACCION_EXITOSA := FALSE;
        P_MENSAJE := 'TRANSACCION FALLIDA';
      END IF;*/
      
      --CANTIDAD DE REGISTROS AFECTADOS
EXCEPTION
    WHEN OTHERS THEN
      P_MENSAJE:= 'ERROR: '||SQLERRM||', CODIGO ERROR:'||SQLCODE;
      --DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM||', CODIGO ERROR:'||SQLCODE);
      P_TRANSACCION_EXITOSA := FALSE;
      ROLLBACK;
    /*WHEN NOMBRE_EXCEPTION_1 THEN
      NULL;
    WHEN NOMBRE_EXCEPTION_3 THEN
      NULL;
    WHEN NOMBRE_EXCEPTION_4 THEN
      NULL;*/
    
END;


SELECT *
FROM DEPARTMENTS;

EXECUTE SP_INSERTAR_EMPLEADO(P_FIRST_NAME => 'JUAN',P_LAST_NAME => 'PEREZ',P_EMAIL => 'juan@gmail.com',P_PHONE_NUMBER => '12312.23423.345',P_HIRE_DATE => sysdate,P_JOB_ID => 'AD_VP',P_SALARY => 21312,P_COMMISSION_PCT => 0.12, P_MANAGER_ID => 101, P_DEPARTMENT_ID => 20);
EXECUTE SP_INSERTAR_EMPLEADO('JUAN','PEREZ','juan2@gmail.com','12312.23423.345',sysdate,'AD_VP',21312,0.12, 101, 20);

SET SERVEROUTPUT ON;

DECLARE
  V_CODIGO_EMPLEADO_INSERTADO INTEGER;
  V_TRANSACCION_EXITOSA BOOLEAN;
  V_MENSAJE VARCHAR2(300);
BEGIN
  SP_INSERTAR_EMPLEADO(
      P_FIRST_NAME => 'JUAN',
      P_LAST_NAME => 'PEREZ',
      P_EMAIL => 'juan667@gmail.com',
      P_PHONE_NUMBER => '12312.23423.345',
      P_HIRE_DATE => sysdate,
      P_JOB_ID => 'AD_VP',
      P_SALARY => 21312,
      P_COMMISSION_PCT => 0.12, 
      P_MANAGER_ID => 101, 
      P_DEPARTMENT_ID => 20,
      P_EMPLOYEE_ID => V_CODIGO_EMPLEADO_INSERTADO,
      P_MENSAJE => V_MENSAJE,
      P_TRANSACCION_EXITOSA=> V_TRANSACCION_EXITOSA);
    DBMS_OUTPUT.PUT_LINE('CODIGO INSERTADO: '||V_CODIGO_EMPLEADO_INSERTADO);
    IF (V_TRANSACCION_EXITOSA) THEN
      DBMS_OUTPUT.PUT_LINE('TRANSACCION_EXITOSA!!!!!');
    ELSE 
      DBMS_OUTPUT.PUT_LINE('TRANSACCION NO EXITOSA :( ');
    END IF;
    DBMS_OUTPUT.PUT_LINE('MENSAJE: '||V_MENSAJE);
END;






--SINTAXIS IF
IF CONDICION THEN
ELSIF  CONDICION THEN
...
ELSIF CONDICION THEN
END IF;


