--ENUNCIADO: ¿Cual es la marca de vehiculo con mas desperfectos?

SELECT *
FROM TBL_VEHICULOS;
SELECT *
FROM TBL_MARCAS;
SELECT *
FROM TBL_MODELOS;
SELECT *
FROM TBL_DESPERFECTOS;
SELECT *
FROM TBL_DESPERFECTO_X_VEHICULO;

--RESPUESTA CORRECTA
SELECT A.NOMBRE_MARCA,
      A.CANTIDAD_DESPERFECTOS,
      ROWNUM AS ORDEN
FROM (
    SELECT C.NOMBRE_MARCA,
          COUNT(1) AS CANTIDAD_DESPERFECTOS
    FROM TBL_VEHICULOS A
    INNER JOIN TBL_MODELOS B
    ON (A.CODIGO_MODELO = B.CODIGO_MODELO)
    INNER JOIN TBL_MARCAS C
    ON (B.CODIGO_MARCA = C.CODIGO_MARCA)
    INNER JOIN TBL_DESPERFECTO_X_VEHICULO D
    ON (A.NUMERO_PLACA = D.NUMERO_PLACA)
    GROUP BY C.NOMBRE_MARCA
    ORDER BY CANTIDAD_DESPERFECTOS DESC
) A
WHERE ROWNUM = 1;

--ESTA NO SERIA LA RESPUESTA CORRECTA PORQUE SOLO MUESTRA EL VALOR
SELECT MAX(CANTIDAD_DESPERFECTOS) AS CANTIDAD_MAXIMA
FROM (
    SELECT C.NOMBRE_MARCA,
          COUNT(1) AS CANTIDAD_DESPERFECTOS
    FROM TBL_VEHICULOS A
    INNER JOIN TBL_MODELOS B
    ON (A.CODIGO_MODELO = B.CODIGO_MODELO)
    INNER JOIN TBL_MARCAS C
    ON (B.CODIGO_MARCA = C.CODIGO_MARCA)
    INNER JOIN TBL_DESPERFECTO_X_VEHICULO D
    ON (A.NUMERO_PLACA = D.NUMERO_PLACA)
    GROUP BY C.NOMBRE_MARCA
    ORDER BY CANTIDAD_DESPERFECTOS DESC
);



SELECT A.*, ROWNUM
FROM (
  SELECT A.*, ROWNUM AS ORDEN_SUBCONSULTA 
  FROM TBL_COLOR A
  ORDER BY NOMBRE_COLOR DESC
) A
WHERE ROWNUM = 1;


--Mostrar los vehiculos con la cantidad de desperfectos y la cantidad de repuestos


SELECT *
FROM  TBL_VEHICULOS A;
SELECT *
FROM TBL_DESPERFECTO_X_VEHICULO;
SELECT * 
FROM TBL_MECANICOS_X_VEHICULOS;
SELECT *
FROM TBL_MECANICOS;

SELECT A.NUMERO_PLACA, 
        A.CANTIDAD_DESPERFECTOS,
        B.CANTIDAD_MECANICOS
FROM (
    SELECT A.NUMERO_PLACA, COUNT(1) CANTIDAD_DESPERFECTOS
    FROM TBL_VEHICULOS A
    INNER JOIN TBL_DESPERFECTO_X_VEHICULO B
    ON (A.NUMERO_PLACA = B.NUMERO_PLACA)
    GROUP BY A.NUMERO_PLACA
  ) A 
INNER JOIN (
    SELECT A.NUMERO_PLACA, COUNT(1) CANTIDAD_MECANICOS
    FROM TBL_VEHICULOS A
    INNER JOIN TBL_MECANICOS_X_VEHICULOS B
    ON (A.NUMERO_PLACA = B.NUMERO_PLACA)
    GROUP BY A.NUMERO_PLACA
) B
ON (A.NUMERO_PLACA = B.NUMERO_PLACA);


/*
INNER JOIN TBL_MECANICOS_X_VEHICULOS C
ON (A.NUMERO_PLACA = C.NUMERO_PLACA);*/

