---sintaxis crear vistas
CREATE OR REPLACE VIEW NOMBRE_VISTA AS
<CONSULTA>;


CREATE OR REPLACE VIEW VW_DESPERFECTOS AS
SELECT A.NUMERO_PLACA,
    B.COSTO_NETO AS COSTO_DESPERFECTO,
    C.NOMBRE_DESPERFECTO,
    C.COSTO_BASE
FROM TBL_VEHICULOS A
INNER JOIN TBL_DESPERFECTO_X_VEHICULO B
ON (A.NUMERO_PLACA = B.NUMERO_PLACA)
INNER JOIN TBL_DESPERFECTOS C
ON (B.CODIGO_DESPERFECTO = C.CODIGO_DESPERFECTO);

SELECT *
FROM VW_DESPERFECTOS;

SELECT count(*) as cantidad_registros
FROM VW_DESPERFECTOS;

SELECT count(1)
FROM VW_DESPERFECTOS;

SELECT sum(costo_desperfecto)
FROM VW_DESPERFECTOS;

SELECT MAX(COSTO_DESPERFECTO) MAXIMO,
    MIN(COSTO_DESPERFECTO) MINIMO
FROM VW_DESPERFECTOS;


SELECT *
FROM VW_DESPERFECTOS
UNION ALL
SELECT 'TOTAL ', SUM(COSTO_DESPERFECTO), ' ', SUM(COSTO_BASE)
FROM VW_DESPERFECTOS;


SELECT NUMERO_PLACA,AVG(COSTO_DESPERFECTO),
      SUM(COSTO_DESPERFECTO)/COUNT(*)
FROM VW_DESPERFECTOS
GROUP BY NUMERO_PLACA;

SELECT NOMBRE_DESPERFECTO,
      COUNT(*) AS CANTIDAD_DESPERFECTOS,
      SUM(COSTO_DESPERFECTO) COSTO
FROM VW_DESPERFECTOS
GROUP BY NOMBRE_DESPERFECTO;

--SE PUEDE UTILIZAR EL OPERADOR DISTINCT PARA ELIMINAR REGISTROS DUPLICADOS
SELECT DISTINCT JOB_ID
FROM EMPLOYEES;

--DIFERENTES PUESTOS QUE ESTAN ASIGNADOS A LOS EMPLEADOS
SELECT COUNT(DISTINCT JOB_ID)
FROM EMPLOYEES;

--CANTIDAD TOTAL DE PUESTOS
SELECT COUNT(*)
FROM JOBS;



SELECT COUNT(1)
FROM TBL_VEHICULOS A
INNER JOIN TBL_DESPERFECTO_X_VEHICULO B
ON (A.NUMERO_PLACA = B.NUMERO_PLACA)
INNER JOIN TBL_DESPERFECTOS C
ON (B.CODIGO_DESPERFECTO = C.CODIGO_DESPERFECTO);


SELECT 'HOLA '||CHR(13)||'OTRA PALABRA'  from dual;


SELECT INITCAP('juan moises perez gimenez')
FROM DUAL;


--EJEMPLO PARA BUSQUEDAS
SELECT *
FROM EMPLOYEES
WHERE LOWER(FIRST_NAME) LIKE LOWER('%Stev %');


select Rpad('alumno',10,'X') from dual;-- retorna 'xyzxalumno'
select lpad('alumno',4,'xyz') from dual;-- retorna 'alum'

--TRIM ELIMINA ESPACIOS AL PRINCIPIO Y AL FINAL, PERO NO EN MEDIO
SELECT *
FROM EMPLOYEES
WHERE LOWER(FIRST_NAME) LIKE '%'||LOWER(TRIM('Stev '))||'%';