/*Nombre de la organización
? Cantidad de usuarios registrados en cada organización
? Cantidad de Tableros por cada organización
? Cantidad de Listas asociadas a cada organización
? Cantidad de Tarjetas asociadas a cada organización*/

SELECT A.NOMBRE_ORGANIZACION,
    NVL(B.CANTIDAD_USUARIOS,0) AS CANTIDAD_USUARIOS,
    NVL(C.CANTIDAD_TABLEROS,0) AS CANTIDAD_TABLEROS,
    NVL(D.CANTIDAD_LISTAS,0) AS CANTIDAD_LISTAS,
    NVL(E.CANTIDAD_TARJETAS,0) AS CANTIDAD_TARJETAS
FROM TBL_ORGANIZACIONES A
LEFT JOIN(
  SELECT CODIGO_ORGANIZACION,
        COUNT(1) AS CANTIDAD_USUARIOS
  FROM TBL_USUARIOS_X_ORGANIZACION
  GROUP BY CODIGO_ORGANIZACION
) B
ON (A.CODIGO_ORGANIZACION = B.CODIGO_ORGANIZACION)
LEFT JOIN (
  SELECT CODIGO_ORGANIZACION, 
        COUNT(1) AS CANTIDAD_TABLEROS
  FROM TBL_TABLERO
  GROUP BY CODIGO_ORGANIZACION
) C
ON (A.CODIGO_ORGANIZACION = C.CODIGO_ORGANIZACION)
LEFT JOIN (
  SELECT B.CODIGO_ORGANIZACION,
        COUNT(1) AS CANTIDAD_LISTAS
  FROM TBL_LISTAS A
  INNER JOIN TBL_TABLERO B
  ON (A.CODIGO_TABLERO = B.CODIGO_TABLERO)
  GROUP BY B.CODIGO_ORGANIZACION
) D
ON (A.CODIGO_ORGANIZACION = D.CODIGO_ORGANIZACION)
LEFT JOIN (
  SELECT C.CODIGO_ORGANIZACION,
        COUNT(1) AS CANTIDAD_TARJETAS
  FROM TBL_TARJETAS A
  INNER JOIN TBL_LISTAS B
  ON (A.CODIGO_LISTA = B.CODIGO_LISTA)
  INNER JOIN TBL_TABLERO C
  ON (B.CODIGO_TABLERO = C.CODIGO_TABLERO)
  GROUP BY C.CODIGO_ORGANIZACION
) E
ON (A.CODIGO_ORGANIZACION = E.CODIGO_ORGANIZACION);


/*
Codigo factura
„h Nombre del plan a facturar
„h Nombre completo del usuario
„h Fecha de pago (Utilizar fecha inicio, mostrarla en formato Dia-Mes-Ano)
„h Ano y Mes de pago (basado en la fecha inicio)
„h Monto de la factura
„h Descuento
„h Total neto*/
drop MATERIALIZED VIEW MVW_FACTURAS ;
CREATE MATERIALIZED VIEW MVW_FACTURAS AS 
SELECT A.CODIGO_FACTURA,
      B.NOMBRE_PLAN,
      C.NOMBRE,
      TO_CHAR(FECHA_INICIO,'DD-MM-YYYY') AS FECHA_PAGO,
      TO_CHAR(FECHA_INICIO,'MM-YYYY') AS ANIO_MES_PAGO,
      A.MONTO,
      A.DESCUENTO,
      A.MONTO - A.DESCUENTO AS TOTAL_NETO
FROM TBL_FACTURACION_PAGOS A
INNER JOIN TBL_PLANES B
ON (A.CODIGO_PLAN = B.CODIGO_PLAN)
INNER JOIN TBL_USUARIOS C
ON (A.CODIGO_USUARIO = C.CODIGO_USUARIO);

